//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.225
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zarabizi.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zarabizi.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado del anclaje.
        /// </summary>
        public static string form_Anclaje_estadoAnclaje {
            get {
                return ResourceManager.GetString("form_Anclaje_estadoAnclaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador de bicicleta.
        /// </summary>
        public static string form_Anclaje_idBicicleta {
            get {
                return ResourceManager.GetString("form_Anclaje_idBicicleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador de estacion.
        /// </summary>
        public static string form_Anclaje_idEstacion {
            get {
                return ResourceManager.GetString("form_Anclaje_idEstacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anclaje ocupado.
        /// </summary>
        public static string form_Anclaje_ocupadoAnclaje {
            get {
                return ResourceManager.GetString("form_Anclaje_ocupadoAnclaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distancia hasta próximo mantenimiento (Km).
        /// </summary>
        public static string form_Bicicleta_distanciaMantenimiento {
            get {
                return ResourceManager.GetString("form_Bicicleta_distanciaMantenimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distancia total recorrida (Km).
        /// </summary>
        public static string form_Bicicleta_distanciaTotal {
            get {
                return ResourceManager.GetString("form_Bicicleta_distanciaTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador de bicicleta.
        /// </summary>
        public static string form_Bicicleta_idBicicleta {
            get {
                return ResourceManager.GetString("form_Bicicleta_idBicicleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de compra de bono.
        /// </summary>
        public static string form_Bono_fechaCompraBono {
            get {
                return ResourceManager.GetString("form_Bono_fechaCompraBono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha final de bono.
        /// </summary>
        public static string form_Bono_fechaFinalBono {
            get {
                return ResourceManager.GetString("form_Bono_fechaFinalBono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de activacion de bono.
        /// </summary>
        public static string form_Bono_fechaInicioBono {
            get {
                return ResourceManager.GetString("form_Bono_fechaInicioBono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador de bono.
        /// </summary>
        public static string form_Bono_idBono {
            get {
                return ResourceManager.GetString("form_Bono_idBono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador de socio.
        /// </summary>
        public static string form_Bono_idSocio {
            get {
                return ResourceManager.GetString("form_Bono_idSocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador de tarifa.
        /// </summary>
        public static string form_Bono_idTarifa {
            get {
                return ResourceManager.GetString("form_Bono_idTarifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        public static string form_Empleado_apellidosEmpleado {
            get {
                return ResourceManager.GetString("form_Empleado_apellidosEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código postal.
        /// </summary>
        public static string form_Empleado_codigopostalEmpleado {
            get {
                return ResourceManager.GetString("form_Empleado_codigopostalEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta bancaria.
        /// </summary>
        public static string form_Empleado_cuentabancariaEmpleado {
            get {
                return ResourceManager.GetString("form_Empleado_cuentabancariaEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Direccion.
        /// </summary>
        public static string form_Empleado_direccionEmpleado {
            get {
                return ResourceManager.GetString("form_Empleado_direccionEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DNI.
        /// </summary>
        public static string form_Empleado_DNIEmpleado {
            get {
                return ResourceManager.GetString("form_Empleado_DNIEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string form_Empleado_emailEmpleado {
            get {
                return ResourceManager.GetString("form_Empleado_emailEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de alta.
        /// </summary>
        public static string form_Empleado_fechaDeAltaEmpleado {
            get {
                return ResourceManager.GetString("form_Empleado_fechaDeAltaEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de nacimiento.
        /// </summary>
        public static string form_Empleado_fechaNacimientoEmpleado {
            get {
                return ResourceManager.GetString("form_Empleado_fechaNacimientoEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador de empleado.
        /// </summary>
        public static string form_Empleado_idEmpleado {
            get {
                return ResourceManager.GetString("form_Empleado_idEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string form_Empleado_nombreEmpleado {
            get {
                return ResourceManager.GetString("form_Empleado_nombreEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Población.
        /// </summary>
        public static string form_Empleado_poblacionEmpleado {
            get {
                return ResourceManager.GetString("form_Empleado_poblacionEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono fijo.
        /// </summary>
        public static string form_Empleado_tlfFijoEmpleado {
            get {
                return ResourceManager.GetString("form_Empleado_tlfFijoEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono móvil.
        /// </summary>
        public static string form_Empleado_tlfMovilEmpleado {
            get {
                return ResourceManager.GetString("form_Empleado_tlfMovilEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de anclajes.
        /// </summary>
        public static string form_Estacion_anclajesEstacion {
            get {
                return ResourceManager.GetString("form_Estacion_anclajesEstacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador de estación.
        /// </summary>
        public static string form_Estacion_idEstacion {
            get {
                return ResourceManager.GetString("form_Estacion_idEstacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string form_Estacion_nombreEstacion {
            get {
                return ResourceManager.GetString("form_Estacion_nombreEstacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación.
        /// </summary>
        public static string form_Estacion_ubicacionEstacion {
            get {
                return ResourceManager.GetString("form_Estacion_ubicacionEstacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string form_Incidencia_fechaIncidencia {
            get {
                return ResourceManager.GetString("form_Incidencia_fechaIncidencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador de incidencia.
        /// </summary>
        public static string form_Incidencia_idIncidencia {
            get {
                return ResourceManager.GetString("form_Incidencia_idIncidencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador de socio.
        /// </summary>
        public static string form_Incidencia_idSocio {
            get {
                return ResourceManager.GetString("form_Incidencia_idSocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incidencia.
        /// </summary>
        public static string form_Incidencia_textoIncidencia {
            get {
                return ResourceManager.GetString("form_Incidencia_textoIncidencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudad.
        /// </summary>
        public static string form_Oficina_ciudadOficina {
            get {
                return ResourceManager.GetString("form_Oficina_ciudadOficina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador de oficina.
        /// </summary>
        public static string form_Oficina_idOficina {
            get {
                return ResourceManager.GetString("form_Oficina_idOficina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provincia.
        /// </summary>
        public static string form_Oficina_provinciaOficina {
            get {
                return ResourceManager.GetString("form_Oficina_provinciaOficina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación.
        /// </summary>
        public static string form_Oficina_ubicacionOficina {
            get {
                return ResourceManager.GetString("form_Oficina_ubicacionOficina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distancia (Km).
        /// </summary>
        public static string form_Recorrido_distanciaRecorrido {
            get {
                return ResourceManager.GetString("form_Recorrido_distanciaRecorrido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de llegada.
        /// </summary>
        public static string form_Recorrido_fechaLlegadaRecorrido {
            get {
                return ResourceManager.GetString("form_Recorrido_fechaLlegadaRecorrido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de salida.
        /// </summary>
        public static string form_Recorrido_fechaSalidaRecorrido {
            get {
                return ResourceManager.GetString("form_Recorrido_fechaSalidaRecorrido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador de bicicleta.
        /// </summary>
        public static string form_Recorrido_idBicicleta {
            get {
                return ResourceManager.GetString("form_Recorrido_idBicicleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador de estación final.
        /// </summary>
        public static string form_Recorrido_idEstacionFinal {
            get {
                return ResourceManager.GetString("form_Recorrido_idEstacionFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador de estación de inicio.
        /// </summary>
        public static string form_Recorrido_idEstacionInicio {
            get {
                return ResourceManager.GetString("form_Recorrido_idEstacionInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador de recorrido.
        /// </summary>
        public static string form_Recorrido_idRecorrido {
            get {
                return ResourceManager.GetString("form_Recorrido_idRecorrido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador de socio.
        /// </summary>
        public static string form_Recorrido_idSocio {
            get {
                return ResourceManager.GetString("form_Recorrido_idSocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción de la reparación.
        /// </summary>
        public static string form_RepararBicicleta_descripcionRepararBicicleta {
            get {
                return ResourceManager.GetString("form_RepararBicicleta_descripcionRepararBicicleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de reparación.
        /// </summary>
        public static string form_RepararBicicleta_fechaRepararBicicleta {
            get {
                return ResourceManager.GetString("form_RepararBicicleta_fechaRepararBicicleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de reparación.
        /// </summary>
        public static string form_RepararBicicleta_fechaRepararEstacion {
            get {
                return ResourceManager.GetString("form_RepararBicicleta_fechaRepararEstacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador de bicicleta.
        /// </summary>
        public static string form_RepararBicicleta_idBicicleta {
            get {
                return ResourceManager.GetString("form_RepararBicicleta_idBicicleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador de empleado.
        /// </summary>
        public static string form_RepararBicicleta_idEmpleado {
            get {
                return ResourceManager.GetString("form_RepararBicicleta_idEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador de reparar bicicleta.
        /// </summary>
        public static string form_RepararBicicleta_idRepararBicicleta {
            get {
                return ResourceManager.GetString("form_RepararBicicleta_idRepararBicicleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string form_RepararEstacion_descripcionRepararEstacion {
            get {
                return ResourceManager.GetString("form_RepararEstacion_descripcionRepararEstacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador de empleado.
        /// </summary>
        public static string form_RepararEstacion_idEmpleado {
            get {
                return ResourceManager.GetString("form_RepararEstacion_idEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador de estación.
        /// </summary>
        public static string form_RepararEstacion_idEstacion {
            get {
                return ResourceManager.GetString("form_RepararEstacion_idEstacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador de reparar estación.
        /// </summary>
        public static string form_RepararEstacion_idRepararEstacion {
            get {
                return ResourceManager.GetString("form_RepararEstacion_idRepararEstacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        public static string form_Socio_apellidosSocio {
            get {
                return ResourceManager.GetString("form_Socio_apellidosSocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código postal.
        /// </summary>
        public static string form_Socio_codigopostalSocio {
            get {
                return ResourceManager.GetString("form_Socio_codigopostalSocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta bancaria.
        /// </summary>
        public static string form_Socio_CuentaBancariaSocio {
            get {
                return ResourceManager.GetString("form_Socio_CuentaBancariaSocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Direccion.
        /// </summary>
        public static string form_Socio_direccionSocio {
            get {
                return ResourceManager.GetString("form_Socio_direccionSocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de alta.
        /// </summary>
        public static string form_Socio_fechaAltaSocio {
            get {
                return ResourceManager.GetString("form_Socio_fechaAltaSocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de nacimiento.
        /// </summary>
        public static string form_Socio_fechaNacimientoSocio {
            get {
                return ResourceManager.GetString("form_Socio_fechaNacimientoSocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador de oficina.
        /// </summary>
        public static string form_Socio_idOficina {
            get {
                return ResourceManager.GetString("form_Socio_idOficina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador de socio.
        /// </summary>
        public static string form_Socio_idSocio {
            get {
                return ResourceManager.GetString("form_Socio_idSocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador de usuario.
        /// </summary>
        public static string form_Socio_idUsuario {
            get {
                return ResourceManager.GetString("form_Socio_idUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string form_Socio_nombreSocio {
            get {
                return ResourceManager.GetString("form_Socio_nombreSocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Población.
        /// </summary>
        public static string form_Socio_poblacionSocio {
            get {
                return ResourceManager.GetString("form_Socio_poblacionSocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono fijo.
        /// </summary>
        public static string form_Socio_tlfFijoSocio {
            get {
                return ResourceManager.GetString("form_Socio_tlfFijoSocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono móvil.
        /// </summary>
        public static string form_Socio_tlfMovilSocio {
            get {
                return ResourceManager.GetString("form_Socio_tlfMovilSocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dias de duración.
        /// </summary>
        public static string form_Tarifa_diasTarifa {
            get {
                return ResourceManager.GetString("form_Tarifa_diasTarifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha final.
        /// </summary>
        public static string form_Tarifa_fechaFinalTarifa {
            get {
                return ResourceManager.GetString("form_Tarifa_fechaFinalTarifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de inicio.
        /// </summary>
        public static string form_Tarifa_fechaInicioTarifa {
            get {
                return ResourceManager.GetString("form_Tarifa_fechaInicioTarifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador de oficina.
        /// </summary>
        public static string form_Tarifa_idOficina {
            get {
                return ResourceManager.GetString("form_Tarifa_idOficina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador de tarifa.
        /// </summary>
        public static string form_Tarifa_idTarifa {
            get {
                return ResourceManager.GetString("form_Tarifa_idTarifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string form_Tarifa_nombreTarifa {
            get {
                return ResourceManager.GetString("form_Tarifa_nombreTarifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio.
        /// </summary>
        public static string form_Tarifa_precioTarifa {
            get {
                return ResourceManager.GetString("form_Tarifa_precioTarifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceder.
        /// </summary>
        public static string lbl_Acceder {
            get {
                return ResourceManager.GetString("lbl_Acceder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administracion de Zarabizi.
        /// </summary>
        public static string lbl_AdministracionZarabizi {
            get {
                return ResourceManager.GetString("lbl_AdministracionZarabizi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anclaje.
        /// </summary>
        public static string lbl_Anclaje {
            get {
                return ResourceManager.GetString("lbl_Anclaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autentificación no tuvo éxito. Por favor, corrija los errores y vuelva a intentarlo..
        /// </summary>
        public static string lbl_AutentificacionNoExito {
            get {
                return ResourceManager.GetString("lbl_AutentificacionNoExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bicicleta.
        /// </summary>
        public static string lbl_Bicicleta {
            get {
                return ResourceManager.GetString("lbl_Bicicleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido a Zarabizi.
        /// </summary>
        public static string lbl_Bienvenido {
            get {
                return ResourceManager.GetString("lbl_Bienvenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bono.
        /// </summary>
        public static string lbl_Bono {
            get {
                return ResourceManager.GetString("lbl_Bono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar contraseña.
        /// </summary>
        public static string lbl_CambiarContraseña {
            get {
                return ResourceManager.GetString("lbl_CambiarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio de contraseña no tuvo éxito. Por favor, corrija los errores y vuelva a intentarlo..
        /// </summary>
        public static string lbl_CambioContraseñaNoExito {
            get {
                return ResourceManager.GetString("lbl_CambioContraseñaNoExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a caracteres de longitud..
        /// </summary>
        public static string lbl_CaracteresLongitud {
            get {
                return ResourceManager.GetString("lbl_CaracteresLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar Contraseña.
        /// </summary>
        public static string lbl_ConfirmarContraseña {
            get {
                return ResourceManager.GetString("lbl_ConfirmarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar nueva contraseña.
        /// </summary>
        public static string lbl_ConfirmarNuevaContraseña {
            get {
                return ResourceManager.GetString("lbl_ConfirmarNuevaContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña actual.
        /// </summary>
        public static string lbl_Contraseñaactual {
            get {
                return ResourceManager.GetString("lbl_Contraseñaactual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La nueva contraseña y la contraseña de confirmación no coinciden.
        /// </summary>
        public static string lbl_ContraseñaNoCoincicde {
            get {
                return ResourceManager.GetString("lbl_ContraseñaNoCoincicde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña nueva.
        /// </summary>
        public static string lbl_ContraseñaNueva {
            get {
                return ResourceManager.GetString("lbl_ContraseñaNueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe de tener un tamaño mínimo de.
        /// </summary>
        public static string lbl_ContraseñasMinimo {
            get {
                return ResourceManager.GetString("lbl_ContraseñasMinimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string lbl_CorreoElectronico {
            get {
                return ResourceManager.GetString("lbl_CorreoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La creación de cuenta no tuvo éxito. Por favor, corrija los errores y vuelva a intentarlo..
        /// </summary>
        public static string lbl_CreaciónCuentaNoExito {
            get {
                return ResourceManager.GetString("lbl_CreaciónCuentaNoExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        public static string lbl_Crear {
            get {
                return ResourceManager.GetString("lbl_Crear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear una nueva cuenta.
        /// </summary>
        public static string lbl_CrearNuevaCuenta {
            get {
                return ResourceManager.GetString("lbl_CrearNuevaCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles.
        /// </summary>
        public static string lbl_Detalles {
            get {
                return ResourceManager.GetString("lbl_Detalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string lbl_Editar {
            get {
                return ResourceManager.GetString("lbl_Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string lbl_Eliminar {
            get {
                return ResourceManager.GetString("lbl_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empleado.
        /// </summary>
        public static string lbl_Empleado {
            get {
                return ResourceManager.GetString("lbl_Empleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string lbl_Error {
            get {
                return ResourceManager.GetString("lbl_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estacion.
        /// </summary>
        public static string lbl_Estacion {
            get {
                return ResourceManager.GetString("lbl_Estacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incidencia.
        /// </summary>
        public static string lbl_Incidencia {
            get {
                return ResourceManager.GetString("lbl_Incidencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información de cuenta.
        /// </summary>
        public static string lbl_InformacionCuenta {
            get {
                return ResourceManager.GetString("lbl_InformacionCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        public static string lbl_Inicio {
            get {
                return ResourceManager.GetString("lbl_Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string lbl_NuevaContraseña {
            get {
                return ResourceManager.GetString("lbl_NuevaContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo.
        /// </summary>
        public static string lbl_Nuevo {
            get {
                return ResourceManager.GetString("lbl_Nuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string lbl_NuevoUsuario {
            get {
                return ResourceManager.GetString("lbl_NuevoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oficina.
        /// </summary>
        public static string lbl_Oficina {
            get {
                return ResourceManager.GetString("lbl_Oficina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recordarme.
        /// </summary>
        public static string lbl_Recordarme {
            get {
                return ResourceManager.GetString("lbl_Recordarme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro.
        /// </summary>
        public static string lbl_Registro {
            get {
                return ResourceManager.GetString("lbl_Registro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reparar bicicleta.
        /// </summary>
        public static string lbl_RepararBicicleta {
            get {
                return ResourceManager.GetString("lbl_RepararBicicleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reparar estación.
        /// </summary>
        public static string lbl_RepararEstacion {
            get {
                return ResourceManager.GetString("lbl_RepararEstacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string lbl_Salir {
            get {
                return ResourceManager.GetString("lbl_Salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de que lo quiere eliminar?.
        /// </summary>
        public static string lbl_SeguroEliminar {
            get {
                return ResourceManager.GetString("lbl_SeguroEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de que quiere eliminar este anclaje?.
        /// </summary>
        public static string lbl_SeguroEliminarAnclaje {
            get {
                return ResourceManager.GetString("lbl_SeguroEliminarAnclaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de que quiere eliminar a este empleado?.
        /// </summary>
        public static string lbl_SeguroEliminarEmpleado {
            get {
                return ResourceManager.GetString("lbl_SeguroEliminarEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de que quiere eliminar a este socio?.
        /// </summary>
        public static string lbl_SeguroEliminarSocio {
            get {
                return ResourceManager.GetString("lbl_SeguroEliminarSocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo siento, un error ha ocurrido mientras se procesaba su solicitud o no tiene privilegios para realizar ésta acción..
        /// </summary>
        public static string lbl_SientoError {
            get {
                return ResourceManager.GetString("lbl_SientoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerca de.
        /// </summary>
        public static string lbl_Sobre {
            get {
                return ResourceManager.GetString("lbl_Sobre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerca de nosotros.
        /// </summary>
        public static string lbl_SobreNosotros {
            get {
                return ResourceManager.GetString("lbl_SobreNosotros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Socio.
        /// </summary>
        public static string lbl_Socio {
            get {
                return ResourceManager.GetString("lbl_Socio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarifa.
        /// </summary>
        public static string lbl_Tarifa {
            get {
                return ResourceManager.GetString("lbl_Tarifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Utilice el formulario a continuación para crear una nueva cuenta..
        /// </summary>
        public static string lbl_UtiliceFormularioNuevaCuenta {
            get {
                return ResourceManager.GetString("lbl_UtiliceFormularioNuevaCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver a la lista.
        /// </summary>
        public static string lbl_VolverLista {
            get {
                return ResourceManager.GetString("lbl_VolverLista", resourceCulture);
            }
        }
    }
}
